org.marmotgraph.component.name=Editor
org.marmotgraph.api.root=/api
org.marmotgraph.component.clientId=${CLIENT_ID}
org.marmotgraph.component.clientSecret=${CLIENT_SECRET}
org.marmotgraph.core.host=${CORE_HOST}

kg.users.searchEndpoint=https://wiki.ebrains.eu/rest/v1/identity/users?search=%s
kg.users.detailEndpoint=https://wiki.ebrains.eu/rest/v1/identity/users/%s
